### ISSUE TITLE
Pom?

### ISSUE THREAD

**Issue by edwardbeckett** [JockiHendry/simple-jpa-demo-laundry#1]
Would you be so kind to publish a pom? the .ivy deps in the imls don't work.

**Comment by JockiHendry** [comment]
Hi Edward,

Dependencies for this project is managed by Griffon.  They are defined in https://github.com/JockiHendry/simple-jpa-demo-laundry/blob/master/griffon-app/conf/BuildConfig.groovy:

```
dependencies {
    runtime 'mysql:mysql-connector-java:5.1.20'
    runtime 'org.hibernate:hibernate-entitymanager:4.3.1.Final'
    runtime 'org.hibernate:hibernate-validator:4.3.0.Final'
    compile('net.sf.jasperreports:jasperreports:5.1.0') {
       exclude 'commons-collections'
    }
}
```

You don't need a separate POM file for this purpose.  If you haven't used Griffon before, you can find more information about dependencies in http://griffon.codehaus.org/guide/latest/guide/configuration.html#dependencyResolution.

For the broken dependency in IDEA, they should only prevent you from using content assist; but your project should still be runnable by executing `griffon run-app`.

To fix the broken dependency in IDEA, you can perform one of the following steps:
1.  Define IDEA project variable `$IVY_CACHE$` that refers to your Ivy cache.  You should've run any Griffon commands to make sure dependencies have been downloaded.
2.  Or, you can delete all IDEA project file (including `.idea` folder) and recreating them by using `griffon integrate-with --idea`.

By the way, this is demo for old version of simple-jpa.  The latest version of simple-jpa is 0.8 and its demo project is https://github.com/JockiHendry/simple-jpa-demo-inventory.

**Comment by edwardbeckett** [comment]
@JockiHendry Thank you for the thorough response. I'm new to Griffon.. but I'm pretty familiar with Spring development ... I'm a bit partial to Maven ;) Gradle is nice but I'm kinda old school there. 

The problem was a dependency on an older library throwing errors for [ShortTypeHandling](http://stackoverflow.com/questions/23846709/groovy-shorttypehandling-classnotfoundexception). 

I attempted deleting the .iml files and rebuilding the app with Griffon but to no avail... the error persisted... I'm pretty certain is was due to the iml... [laundry-griffonPluginFixes.iml](https://github.com/JockiHendry/simple-jpa-demo-laundry/blob/918b956ecdcc21dd05868739ded5acebf057891d/laundry-griffonPluginFixes.iml#L11-71)

Thanks for the link to the newer demo ... I'll try that out... ;)

**Comment by JockiHendry** [comment]
I compiled binaries for simple-jpa using Groovy 2.3,  unaware that Groovy 2.3 binaries is not compabitle with Groovy 2.2.

Try to upgrade Groovy in Griffon lib to at least Groovy 2.3.  By default, Griffon 1.5 comes with Groovy 2.2.  This version doesn't have required classes for new binaries so it throws `ClassNotFoundException`.  You can find a tutorial for this in http://www.jroller.com/aalmiray/entry/running_griffon_with_an_alternate.

Or, you may want to recompile simple-jpa binary in default Griffon configuration (Groovy 2.2).  Retrieve simple-jpa stable source and run `griffon package-plugin`.  This will generate a zip distribution file.  Then, in your project, run `griffon install-plugin <path-to-zip-file>`.
